export const ConfigKeys = {
  API_TOKEN: 'dynamic.apiToken',
  PUBLIC_KEY: 'dynamic.publicKey',
  ENVIRONMENT_ID: 'dynamic.environmentId',
  DB_HOST_KEY: 'database.host',
  DB_PORT_KEY: 'database.port',
  DB_USERNAME_KEY: 'database.username',
  DB_PASSWORD_KEY: 'database.password',
  DB_NAME_KEY: 'database.database',
  DB_SSL_ENABLED: 'database.sslEnabled',
  DB_SSL_REJECT_UNAUTHORIZED: 'database.sslRejectUnauthorized',
  RPC_URL: 'blockchain.rcpUrl',
  ENCRYPTION_KEY: 'blockchain.encryptionKey',
  FUNDER_PRIVATE_KEY: 'blockchain.funderPrivateKey',
  CONFIG_BLOCKCHAIN: 'blockchain',
  CONFIG_DATABASE: 'database',
  CONFIG_DYNAMIC: 'dynamic',
};
